In [1]:
import pandas as pd

In [3]:
df_lm = pd.read_csv(r"G:\work\logistica\test\zj_lm_20190311.csv")

In [4]:
df_OR = pd.read_csv(r"G:\work\logistica\test\zj_order_20190311.csv")

In [7]:
df_ZJ = pd.read_excel(r"G:\work\basic\province\DEC18\浙江(所在省).xlsx")

In [5]:
df_lm.head()

,CENTER,LM_NAME,LAT_A,LGN_A,TARGET,ORDERNO_B,LAT_B,LGN_B,DIS,KX07_PROVINCEID,KX08_CITYID
0,C,UDC·时代大厦,30.246301,120.21576,T,690000000001008318122220917790,30.259648,120.192594,2.6777,浙江省,杭州市
1,C,UDC·时代大厦,30.246301,120.21576,T,600104833000008318121597201978,30.259648,120.192594,2.6777,浙江省,杭州市
2,C,UDC·时代大厦,30.246301,120.21576,T,690000000001008318120620539524,30.259648,120.192594,2.6777,浙江省,杭州市
3,C,UDC·时代大厦,30.246301,120.21576,T,690000000001008318122020873212,30.259648,120.192594,2.6777,浙江省,杭州市
4,C,UDC·时代大厦,30.246301,120.21576,T,690000000001008318121220687403,30.259648,120.192594,2.6777,浙江省,杭州市

In [6]:
df_OR.head()

,ORDERNO,SITENAME,SITEADDRESS_ALL,SITE_LAT,SITE_LNG,RE_ADDRESS,RE_PROVINCE,RE_CITY,RE_DISTRICT,RE_LAT,RE_LNG,DIS
0,690000000001008318120420486860,杭州福通营业部,浙江省杭州市浙江省杭州市江干区塘工局路358号,30.277537,120.224026,浙江杭州市江干区市民街航空大厦1幢19层1908,浙江省,杭州市,江干区,30.237320,120.208872,4.7081
1,690000000001008318120120425595,杭州滨兴营业部,浙江省杭州市浙江杭州市滨江区湖头陈北路16号院内京东,30.162450,120.146505,东方郡西区25幢2单元1204室,浙江省,杭州市,滨江区,30.197638,120.212547,7.4654
2,690000000001008318121920845907,杭州交通营业部,浙江省杭州市浙江省杭州市余杭区良渚镇良渚村九组白池圩3号,30.379881,120.051016,都市阳光嘉苑8幢2单元701,浙江省,杭州市,西湖区,30.336536,120.067630,5.0822
3,690000000001008318120220444700,杭州交通营业部,浙江省杭州市浙江省杭州市余杭区良渚镇良渚村九组白池圩3号,30.379881,120.051016,浙江杭州市余杭区旺君国际2楼农商行,浙江省,杭州市,余杭区,30.346382,120.076303,4.4503
4,690000000001008318120820582205,杭州丁兴营业部,浙江省杭州市浙江省杭州市江干区丁桥镇明珠街1275号,30.356015,120.242065,阳光城翡丽湾9幢4单元601,浙江省,杭州市,江干区,30.347232,120.206328,3.5695

In [9]:
df_ZJ.head()

,Unnamed: 0,订单编号,订单状态,订单子状态,订单挂起原因,安装失败原因,订单来源,店铺,订单金额,订单生成时间,...,营业厅送货方式,是否线下模式,是否线下转线上,线下转线上原因,营业厅送货iccid,所在省,所在市,所在县,号码归属省,号码归属市
0,76,600104833000008318120495751796,拆机中,NaN,NaN,NaN,WAP客户端/服务,WAP店铺,0.0,2018-12-04 23:54:55,...,NaN,NaN,NaN,NaN,NaN,浙江,绍兴市,绍兴县,浙江省,绍兴市
1,107,690000000001008318120420508887,拆机中,正式单成功,NaN,NaN,小米,WAP店铺,0.0,2018-12-04 23:54:17,...,NaN,NaN,NaN,NaN,NaN,浙江,温州市,苍南县,浙江省,温州市
2,238,690000000001008318120420508800,交易完成,NaN,NaN,NaN,VIVO,WAP店铺,0.0,2018-12-04 23:50:55,...,NaN,NaN,NaN,NaN,NaN,浙江,杭州市,滨江区,浙江省,杭州市
3,260,600404864000008318120495751308,交易完成,NaN,NaN,NaN,WAP客户端/服务,WAP店铺,0.0,2018-12-04 23:50:04,...,NaN,NaN,NaN,NaN,NaN,浙江,台州市,临海市,宁夏回族自治区,中卫市
4,283,690000000001008318120420508753,交易完成,NaN,NaN,NaN,京东,WAP店铺,0.0,2018-12-04 23:49:06,...,NaN,NaN,NaN,NaN,NaN,浙江,杭州市,余杭市,浙江省,杭州市

In [10]:
df1 = pd.merge(df_OR,df_ZJ,how="left",left_on="ORDERNO",right_on='订单编号')

In [45]:
df1.to_excel(r"G:\work\logistica\test\orderInfo.xlsx")

In [13]:
df1.columns

Index(['ORDERNO', 'SITENAME', 'SITEADDRESS_ALL', 'SITE_LAT', 'SITE_LNG',
       'RE_ADDRESS', 'RE_PROVINCE', 'RE_CITY', 'RE_DISTRICT', 'RE_LAT',
       'RE_LNG', 'DIS', 'Unnamed: 0', '订单编号', '订单状态', '订单子状态', '订单挂起原因',
       '安装失败原因', '订单来源', '店铺', '订单金额', '订单生成时间', '交易完成时间', '发货时间', '物流单回填时间',
       '入网用户姓名', '入网身份证号', '入网手机号', '收货人姓名', '收货地址', '收货人电话号码', '邮编',
       '所在省 / 市 / 县', '号码归属地', 'CPS推荐人', '订单备注', '物流单号', '物流签收时间', '承运商',
       '大小卡类型', '写卡渠道', '销售品编号', '销售品名称', '销售品类型', '套餐', '主号码', '副号码', '现金预存款',
       '靓号低消', '靓号等级', '靓号预存款', '营业厅送货方式', '是否线下模式', '是否线下转线上', '线下转线上原因',
       '营业厅送货iccid', '所在省', '所在市', '所在县', '号码归属省', '号码归属市'],
      dtype='object')

In [17]:
df1["订单状态"][0]

'拆机中'

In [22]:
def get_activation(str1):
    if str1 == "交易完成":
        return '1'
    else:
        return '0'

In [29]:
df1['激活量'] = df1["订单状态"].apply(get_activation)

In [41]:
def get_logistica(str1):
    if str1 == null:
        return '0'
    else:
        return '1'

In [42]:
df1['发货量'] = df1["物流单号"].apply(get_logistica)

In [ ]:
def get_sign(str1,str2):
    if str1 != null:
        return '1'
    elif：
        str1 == null & str2 != "交易完成"
    else:
        return '1'

In [43]:
df1[['发货量',"物流单号"]]

     发货量           物流单号
0      1  VB49916788095
1      1  VB48438744351
2      1  VB48083292246
3      1  VB48350455576
4      1  VB50646797353
5      1  VB51164355115
6      1  VB49146425871
7      1  VB48349392453
8      1  VB50133822491
9      1  VB48653757154
10     1  VB49160707341
11     1  VB47957817084
12     1  VB48509914596
13     1  VB51172569512
14     1  VB48854891573
15     1  VB47869631283
16     1  VB49891848495
17     1  VB47604934285
18     1  VB49244821264
19     1  VB48686354511
20     1  VB49502676300
21     1  VB49164979743
22     1  VB48486263652
23     1  VB48219763885
24     1  VB48653756992
25     1  VB48990880186
26     1  VB49081585184
27     1  VB49281547420
28     1  VB48966399576
29     1  VB50363481615
...   ..            ...
5220   1  VB49229776024
5221   1  VB48042932361
5222   1  VB49895812890
5223   1  VB48691911380
5224   1  VB49365953711
5225   1  VB49622245746
5226   1  VB49777659341
5227   1  VB50778868173
5228   1  VB47606261964
5229   1  VB49334532343
5230   1  VB49135178341
5231   1  VB48910207872
5232   1  VB48134756725
5233   1  VB50935728793
5234   1  VB51030352553
5235   1  VB48739428216
5236   1  VB47971733364
5237   1  VB48886656114
5238   1  VB48307964040
5239   1  VB48419656482
5240   1  VB48420615574
5241   1  VB48693937622
5242   1  VB48115281200
5243   1  VB48974383905
5244   1  VB49334532181
5245   1  VB50533457295
5246   1  VB48454713230
5247   1  VB48980352912
5248   1  VB49019121981
5249   1  VB49880982093

[5250 rows x 2 columns]

In [44]:
df1['物流签收时间'].isnull().value_counts()

False    5083
True      167
Name: 物流签收时间, dtype: int64

In [31]:
df1['订单状态'].value_counts()

交易完成    3191
拆机中     2039
订单关闭      11
退款成功       9
Name: 订单状态, dtype: int64